services:
  nn_laser_spot_tracking:
    build:
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/cu118
        TORCH_SUFFIX: +cu118
    gpus: all
    environment:
      - TRACKING_ENABLE=true
      # Azure Kinect FPS: valid values are 5, 15, 30.
      - K4A_FPS=30
      # Higher resolution is OK on GPU.
      - COLOR_RESOLUTION=1536P
      - NODES_REQUIRED=true
